name: React App GitHub Deploy
on: 
  push:
    branches: [main] 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
    
      - name: Install & Build
        run: npm i && npm run build
    
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist/dashboard2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
